lane :test do
  a = fiv_select_branding

  puts"selected branding key from fiv_select_branding action #{a}"

  b = fiv_select_branding(branding_folder: "../e2e")

  puts"selected branding key from fiv_select_branding action #{b}"

  puts"selected branding key from fiv_select_branding action ENV #{ENV['FIV_SELECTED_BRANDING_KEY']}"
  puts"selected branding path from fiv_select_branding action ENV #{ENV['FIV_SELECTED_BRANDING_PATH']}"

  c = fiv_select_brandings
  puts "
          ***********************************************
            Selected branding keys from fiv_select_brandings action = #{c}
          ***********************************************
        "
  d = fiv_select_brandings(branding_folder: "../src")
  puts "
          ***********************************************
            Selected branding keys from fiv_select_brandings action = #{d}
          ***********************************************
        "
end
