before_all do |lane, options|
  ENV["CLIENT"] = options[:client]
  ENV["ENV"] = options[:env]
end

lane :select_client do |options|
  client = fiv_select_client()

  puts("This client is selected #{client}")
end

lane :select_clients do |options|
  clients = fiv_select_clients()

  puts("These clients are selected #{clients}")
end

lane :select_client_env do
  client = fiv_select_client()
  env = fiv_select_env(client: client)

  puts("This client #{client} and environment #{env} is selected")
end
