
git_url = "https://bitbucket.org/fivethree/fastlane-certs"

update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Build and release a test version to testflight"
  lane :fiv_testflight do

  # ensure_git_status_clean   
  match(
    git_url: git_url,
    type: "appstore",
  ) 
  version_and_build_no = fiv_update_version_and_build_no(
    ios: true,
    pathToConfigXML: "./config.xml"
  )

  fiv_bump_version(
    message: "Version Bump: build #{version_and_build_no[:build_no]}, version: #{version_and_build_no[:version]}"
    )
  push_to_git_remote

  ionic(
    platform: 'ios',
    release: true
  )
  automatic_code_signing(
        path: "platforms/ios/fivethree-fastlane.xcodeproj",
        use_automatic_signing: false,
        team_id: "2K6ELPY322"
    )
  gym
  pilot

  notification(subtitle: "Fastlane finished successfully", message: "Nice")
  rocket

  end
end

platform :android do
  
  desc "Build and release a test version to testflight"
  lane :fiv_alpha do
  fiv_update_version_and_build_no(
    ios: false,
    pathToConfigXML: "./config.xml"
  )
  ionic(
    platform: 'android',
    release: true
  )
  end
end
