
update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Build and release a test version to testflight"
  lane :fiv_testflight do

  # ensure_git_status_clean   
  match
  version_and_build_no = fiv_version(
    ios: true,
    pathToConfigXML: "./config.xml"
  )

  ionic(
    platform: 'ios',
    release: true
  )
  automatic_code_signing(
        path: "platforms/ios/fivethree-fastlane.xcodeproj",
        use_automatic_signing: false,
        team_id: "2K6ELPY322"
    )
  gym
  pilot
  end
end

platform :android do
  
  desc "Build and release a test version to testflight"
  lane :fiv_alpha do
  fiv_update_version_and_build_no(
    ios: false,
    pathToConfigXML: "./config.xml"
  )
  ionic(
    platform: 'android',
    release: true
  )
  end
end
